[build]
  publish = "dist/public"
  command = "bun run build"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/api/authenticate"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"